### ISSUE TITLE
Use case: do not offer "outdated" components in selection

### ISSUE THREAD

**Issue by leoselig** [neXenio/strangelog#21]
When a component is no longer maintained it is annoying to still have it displayed in the available component options. While the component entry is still needed in the `.strangelogrc` to be able to compile older changelog entries, it could be configured to no longer be offered when adding new entries.
This is somewhat related to #16.

### Possible solution

Transform `.strangelogrc` format to something like this:
```yaml
path: ./changelog
components:
  component1:
    title: "First Component"
    enabled: true
  component2:
    title: "Unmaintained Component"
    enabled: false
```
